resources:
  - url: http://127.0.0.1:5000/baby-dresser-card.js
    type: module
views:
  - cards:
      - type: custom:baby-dresser
        name: Baby Dresser Card Development
        entity: sun.sun
        test_gui: true
